# -*- coding: utf-8 -*-
import locale
import time
import logging
import pip
from datetime import datetime,date,timedelta
from odoo import api, fields, models, _
from odoo.exceptions import UserError
try:
    from odoo.tools.misc import xlsxwriter
except ImportError:
    import xlsxwriter
import io
import json
import datetime
from odoo.tools import date_utils
from babel.numbers import format_decimal

_logger = logging.getLogger(__name__)

class CrReport(models.Model):
    _name = 'cr.report'
    _description = 'Base custom report'
    _inherit = ['mail.thread', 'mail.activity.mixin', 'avatar.mixin']
    
    
    # Fields declaration
    name = fields.Char(string="Report Name" , default='Custom Report Register')
    from_date = fields.Date(string="From Date", required=True, default=fields.Date.today, index=True,
                 widget='date', help="Starting date for genarate report.")
    to_date = fields.Date(string="To Date", required=True,
                 default=fields.Date.today, index=True, help="End date for genarate report.")
    
    partner_ids = fields.Many2many(comodel_name='res.partner',
        string="Partner Name", index=True,domain=[('active', '=', True)])
        
    output_type = fields.Selection([('excel', 'Excel'),('pdf', 'PDF')], 
                  nolabel=True, required=True, widget='selection')

    #Entry info
    generate_date = fields.Datetime('Generated Date', store=True, readonly=True, default=time.strftime('%Y-%m-%d %H:%M:%S'))
    generate_user_id = fields.Many2one('res.users', 'Generated By',store=True, readonly=True, default=lambda self: self.env.user.id)

    def write(self,vals):
        vals.update({'generate_date': time.strftime('%Y-%m-%d %H:%M:%S'),'generate_user_id':self.env.user.id})
        return super(CrReport, self).write(vals)

    @api.onchange('from_date', 'to_date')
    def onchange_date_validations(self):
        if self.from_date > fields.Date.today() or self.to_date > fields.Date.today():
           raise UserError(_("Future date is not allowed. Kindly choose correct from & to date."))


    def print_report(self):
        for rec in self:
            current_datetime = datetime.datetime.now() + timedelta(hours=5, minutes=30)
            data = {
                'from_date': rec.from_date.strftime("%d/%m/%Y"),
                'to_date': rec.to_date.strftime("%d/%m/%Y"),
                'report_taken_by': self.env.user.partner_id.name,
                'taken_date': str(current_datetime.strftime("%d/%m/%Y %H:%M:%S")),
                'partner_list': [partner.name for partner in rec.partner_ids],
                'company_name': rec.env.user.company_id.name,
                'company_street': rec.env.user.company_id.street,
                'company_state': rec.env.user.company_id.state_id.name,
                'trans_details': [{
                              'trans_no': trans_details.name,
                              'date': trans_details.entry_date.strftime("%d/%m/%Y"),
                              'partner_name': trans_details.partner_id.name,
                              'division':trans_details.division_id.name,
                              'department':trans_details.department_id.name,
                              'net_amt':trans_details.net_amt,
                              'product_details': [{
                                                  'product_name': trans_line.description,
                                                  'product_category': trans_line.product_id.product_tmpl_id.categ_id.name,
                                                  'brand': trans_line.brand_id.name,
                                                  'uom': trans_line.uom_id.name,
                                                  'qty': trans_line.qty,
                                                  'unitprice_wt': trans_line.unitprice_wt,
                                                  'unit_price': trans_line.unit_price,
                                                  'tax': trans_line.tax_amt,
                                                  'disc_amt': trans_line.disc_amt,
                                                  'line_tot_amt': trans_line.line_tot_amt 
                                                 } for trans_line in self.env['ct.transaction.line'].search([('header_id', '=', trans_details.id)])]

                              } for trans_details in self.env['ct.transaction'].search([('entry_date', '>=', rec.from_date),
                                                                                     ('entry_date', '<=', rec.to_date),\
                                                                                     ('status', 'in', ['approved'])],\
                                                                                     order='entry_date asc')\
                                                                                     if trans_details.partner_id in rec.partner_ids or not rec.partner_ids],
                                                                                     
            }
            if not [trans['product_details'] for trans in data['trans_details']]:
                raise UserError("No data available in given date range.")
            if not [trans_line['product_name'] for trans in data['trans_details'] for trans_line in trans['product_details']]:
                raise UserError("No product data available in given date range.")
            excel = {
                'type': 'ir.actions.report',
                'data': {'model': 'cr.report',
                         'options': json.dumps(data,
                                               default=date_utils.json_default),
                         'output_format': 'xlsx',
                         'report_name': 'Standard_Excel_Report_Template',
                         },
                'report_type': 'xlsx',
            }

            pdf = {'data': data}
            return pdf if rec.output_type == 'pdf' else excel       
    def get_xlsx_report(self, data, response):
        """this is used to print the report of all records"""
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})
        sheet = workbook.add_worksheet()
        # Formats
        format1 = workbook.add_format(
            {'font_size': 10, 'align': 'center', 'bold': True, 'border': 1, 'text_wrap': True,'font_name': 'Arial'})
        #format1.set_font_color('#000080')
        format2 = workbook.add_format(
            {'font_size': 10, 'bold': True, 'border': 1, 'bg_color': '#a5f9f7', 'text_wrap': True,'font_name': 'Arial'})

        format2.set_align('center')
        format11 = workbook.add_format({'font_size': 10, 'bold': True, 'border': 1,'font_name': 'Arial', 'text_wrap': True})

        sno_format = workbook.add_format({'font_size': 10,'valign':'vcenter','font_name': 'Arial','border': 1})
        sno_format.set_align('center')
        trans_head_format = workbook.add_format({'font_size': 10, 'align':'left','valign':'vcenter',\
                   'font_name': 'Arial','border': 1, 'text_wrap': True})
        trans_line_format_str = workbook.add_format({'font_size': 10, 'font_name': 'Arial','border': 1, 'text_wrap': True})
        trans_line_format_str.set_align('left')
        trans_line_format_float = workbook.add_format({'font_size': 10, 'font_name': 'Arial','border': 1, 'text_wrap': True})
        trans_line_format_float.set_align('right')
        grand_total_format = workbook.add_format({'font_size': 10, 'bold':True, 'font_name': 'Arial','border': 1, 'bg_color': '#DCDCDC', 'text_wrap': True})
        grand_total_format.set_align('center')
        grand_total_format_ans = workbook.add_format({'font_size': 10, 'bold':True,\
                        'font_name': 'Arial','border': 1, 'bg_color': '#DCDCDC', 'text_wrap': True})
        
        grand_total_format_ans.set_align('right')
        
    
        sheet.merge_range(0, 0, 0, 13 ,
                          "%s, %s, %s"%(data['company_name'],data['company_street'],data['company_state']), format1)

        sheet.merge_range(1, 0, 1, 13,
                          'Standard Excel Report Template', format1)

        sheet.merge_range(2, 0, 2, 3,
                          "From Date %s: %s"%(' ' * 11,data['from_date']), format11)
        sheet.merge_range(3, 0, 3, 3,
                          "Partner%s: %s"%(' ' * 17, 'Limited' if data['partner_list'] else 'All'), format11)
        sheet.merge_range(4, 0, 4, 3,
                          "Report Taken By   : %s" %(data['report_taken_by']), format11)

        sheet.merge_range(2, 10, 2, 13,
                          "To Date %s: %s"%(' ' * 18,data['to_date']), format11)
        
        sheet.merge_range(3, 10, 4, 13,
                          "Taken Date & Time  : %s" %(data['taken_date']), format11)


        sheet.write(7, 0, "S.No", format2)
        sheet.set_column('A:A', 5)
        sheet.write(7, 1, "Ref No", format2)
        sheet.set_column('B:B', 16)
        sheet.write(7,2, "Date", format2)
        sheet.set_column('C:C', 9)
        sheet.write(7,3, "Partner Name", format2)
        sheet.set_column('D:D', 14)
        sheet.write(7,4, "Net Amount", format2)
        sheet.set_column('E:E', 14)
        sheet.write(7,5, "Description", format2)
        sheet.set_column('F:F', 18)
        sheet.write(7,6, "Category", format2)
        sheet.set_column('G:G', 18)
        sheet.write(7,7, "Brand", format2)
        sheet.set_column('H:H', 14)
        sheet.write(7,8, "UOM", format2)
        sheet.set_column('I:I', 6)
        sheet.write(7,9, "Qty", format2)
        sheet.set_column('J:J', 10)
        sheet.write(7,10, "Unit Price", format2)
        sheet.set_column('K:K', 12)
        sheet.write(7,11, "Discount", format2)
        sheet.set_column('L:L', 12)
        sheet.write(7,12, "Tax", format2)
        sheet.set_column('M:M', 12)
        
        sheet.write(7,13, "Total(WT)", format2)
        sheet.set_column('N:N', 12)



        row_num = 8
        s_no = 1
        grand_total = 0
        trans_line_len = 8
        grand_total = 0
        head_row = 8
        for trans in data['trans_details']:
            if trans['product_details']:
                trans_line_len += (len(trans['product_details']) - 1)
                if head_row == trans_line_len:
                    sheet.write(head_row, 0, s_no, sno_format)
                    print(type(trans['trans_no']),trans['trans_no'])
                    sheet.write(head_row, 1, trans['trans_no'] or '', trans_head_format)
                    sheet.write(head_row, 2, trans['date'], trans_head_format)
                    sheet.write(head_row, 3, trans['partner_name'], trans_head_format)
                    sheet.write(head_row, 4, self.currency_indian_format(trans['net_amt']), trans_line_format_float)
                else:
                    sheet.merge_range(head_row, 0, trans_line_len, 0, s_no, sno_format)
                    sheet.merge_range(head_row, 1, trans_line_len, 1, trans['trans_no'], trans_head_format)
                    sheet.merge_range(head_row, 2, trans_line_len, 2, trans['date'], trans_head_format)
                    sheet.merge_range(head_row, 3, trans_line_len, 3, trans['partner_name'], trans_head_format)
                    sheet.merge_range(head_row, 4, trans_line_len, 4, self.currency_indian_format(trans['net_amt']), trans_line_format_float)
                for trans_line in trans['product_details']:
                    sheet.write(row_num, 5, trans_line['product_name'], trans_line_format_str)
                    sheet.write(row_num, 6, trans_line['product_category'], trans_line_format_str)
                    sheet.write(row_num, 7, trans_line['brand'] or '', trans_line_format_str)
                    sheet.write(row_num, 8, trans_line['uom'] or '', trans_line_format_str)
                    sheet.write(row_num, 9, "{:.3f}".format(trans_line['qty']), trans_line_format_float)
                    sheet.write(row_num, 10, self.currency_indian_format(trans_line['unit_price']), trans_line_format_float)
                    sheet.write(row_num, 11, self.currency_indian_format(trans_line['disc_amt']), trans_line_format_float)
                    sheet.write(row_num, 12, self.currency_indian_format(trans_line['tax']), trans_line_format_float)
                    sheet.write(row_num, 13, self.currency_indian_format(trans_line['line_tot_amt']), trans_line_format_float)
                    
                    row_num += 1
                grand_total += trans['net_amt']#trans_line['line_tot_amt']
                trans_line_len += 1
                head_row = trans_line_len
                s_no += 1

        sheet.merge_range(1 + head_row, 2, 1 + head_row, 3,"Grand Total", grand_total_format)
        sheet.write(1 + head_row,4,self.currency_indian_format(grand_total), grand_total_format_ans)
        workbook.close()
        output.seek(0)
        response.stream.write(output.read())
        output.close()

    def print_report_button(self):
        if self.output_type == 'excel':
            return self.print_report()
        else:
            self.print_report()
            report_action = self.env.ref('cr_report.cr_report_register')
            return report_action.report_action(self)


    def date_indian_format(self):
        '''date indian format'''
        date_contents = date_pyformat.split("-")
        date_indian = date_contents[2]+"/"+date_contents[1]+"/"+date_contents[0]
        return date_indian

    def currency_indian_format(self,amount):
        '''currency indian format'''
        try:
            locale.setlocale(locale.LC_ALL, 'en_IN')
            formatted_amount = locale.format_string("%0.2f", amount, grouping=True)
            return formatted_amount
        except Exception:
            return "{:.2f}".format(amount)


  
